application: grooming-standard-dev
version: 1
runtime: python27
threadsafe: true
api_version: 1

default_expiration: "10m"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: (.*)/
  static_files: angular-seed/app\1/index.html
  upload: angular-seed/app/index\.html
  mime_type: text/html; charset=utf-8

- url: (/.*\.css)
  static_files: angular-seed/app\1
  upload: angular-seed/app/.*\.css
  mime_type: text/css; charset=utf-8

- url: (/.*\.html)
  static_files: angular-seed/app\1
  upload: angular-seed/app/.*\.html
  mime_type: text/html; charset=utf-8

- url: (/.*\.js)
  static_files: angular-seed/app\1
  upload: angular-seed/app/.*\.js
  mime_type: text/javascript; charset=utf-8

- url: (/.*\.jpg)
  static_files: angular-seed/app\1
  upload: angular-seed/app/.*\.jpg
  mime_type: text/javascript; charset=utf-8

- url: (/.*\.map)
  static_files: angular-seed/app\1
  upload: angular-seed/app/.*\.map
  mime_type: text/javascript; charset=utf-8




libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
